collection = set()

collection.add(1)
collection.add(5)
collection.add(5)
collection.add("Naziya")
collection.add("coding")
collection.add("Python")
collection.remove("Python")
print(collection.pop())